install: travis_wait 30 mvn install
sudo: required
language: java
jdk: openjdk8
services: docker

install:
# Install Nextflow
  - mkdir nextflow
  - cd nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s $PWD/nextflow /usr/local/bin/nextflow

# Install ExOrthist
  - git clone https://github.com/biocorecrg/ExOrthist.git
  - cd ExOrthist
 
# Run the pipeline
script:
   - nextflow run main.nf -with-docker 
