# Generic options
wf: "main"
# Schema validation default options
validate_params: true
# Notification options
hook_url: null
email: null
# Main pipeline options
cluster: "./test/hg38_mm10_bosTau9.tab"
genomes: "./test/GENOMES/*_gDNA-subsetted.fasta.gz"
annotations: "./test/GTF/*_annot-subsetted.gtf.gz"
alignmentnum: 1000
orthogroupnum: 500
evodists: "./test/evodists.new.txt"
long_dist: "2,0.10,0.40,0.15"
medium_dist: "2,0.30,0.60,0.20"
short_dist: "2,0.50,0.60,0.25"
# Additional data
extraexons: null
bonafide_pairs: null
orthopairs: null
prevaln: null
# Output folder
output: "./output_test"
# Plot pipeline specific options
geneID: "ENSG00000159055"
output_plot: "./output_plot"
relevant_exs: "chr21:32274830-32274896"
ordered_species: "hg38,mm10,bosTau9"
isoformID: "ENSP00000290130"
sub_orthologs: null
