on:
  push:
  workflow_dispatch:

name: test-ExOrthist

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Install Nextflow
      uses: nf-core/setup-nextflow@v1.2.0
      with:
        version: 20.04.1
    - run: nextflow run ${GITHUB_WORKSPACE} -with-docker
