on:
  push:
  workflow_dispatch:

name: test-ExOrthist

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Install Nextflow
      uses: nf-core/setup-nextflow@v2.0.0
    - run: nextflow run ${GITHUB_WORKSPACE} -with-docker
